// ═════════════════════════════════════════════════════════════════════════
// [SHARED] Platform infrastructure. Single entry point for intelligence
// generation. During the Gemini-only phase this is a thin wrapper; the
// Claude path lives behind a flag for an easy re-enable when we're ready
// to ship public model selection.
//
// Returns { text, model_used, model_requested, latency_ms, tokens_used,
//           usage, cost_cents }.
// ═════════════════════════════════════════════════════════════════════════

import { call as geminiCall, estimateCostCents as geminiCost } from './gemini.js';

const GEMINI_MODEL = 'gemini-2.5-flash';

async function runGemini({ system, user, max_tokens, temperature }) {
  const res = await geminiCall({
    model: GEMINI_MODEL,
    system, user, max_tokens, temperature, json: true,
  });
  return {
    text: res.text,
    model: res.model || GEMINI_MODEL,
    usage: res.usage || {},
    cost_cents: geminiCost(res.usage, res.model),
  };
}

// Public entry. `model` argument is accepted but ignored during the
// Gemini-only phase — every brief is generated by Gemini. Keeping the
// argument means callers (intelligence.js, compare-models.js) don't need
// to be touched when we re-enable provider selection.
export async function generateIntelligence({ system, user, model: _model, max_tokens = 6000, temperature = 0.6 } = {}) {
  const start = Date.now();
  const r = await runGemini({ system, user, max_tokens, temperature });
  return {
    text: r.text,
    model_used: 'gemini',
    model_requested: 'gemini',
    latency_ms: Date.now() - start,
    tokens_used: r.usage?.total_tokens
              || ((r.usage?.input_tokens || 0) + (r.usage?.output_tokens || 0)),
    usage: r.usage,
    cost_cents: r.cost_cents,
    raw_model: r.model,
  };
}
